### ISSUE TITLE
Crash when NGON rotate set to zero

### ISSUE THREAD

**Issue by paxofsnax** [museumsvictoria/spatial_audio_server#188]
Audio Server Crashed when NGON vertices set to 0 with and errant drag to far to the left ns Rotate set to Zero.
`thread 'soundscape' panicked at 'attempt to calculate the remainder with a divisor of zero', src/lib/soundscape/movement/ngon.rs:195:39
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'failed to send movement update to soundscape thread: "SendError(..)"', libcore/result.rs:945:5
logout
`

**Comment by paxofsnax** [comment]
I will test and see if I can reproduce this issue/ crash on another clone of the Audio Server file and computer.

**Comment by mitchmindtree** [comment]
Thanks for the report!

The Ngon vertices parameter allows for controlling the number of vertices used to describe an equilateral polygon that is used to represent the path of a virtual sound source around the centre of an installation. I wonder if the correct fix for this is just to change the minimum bound of the slider to a value of 1 or 2, as I guess a polygon with 0 sides doesn't make a lot of sense? I'll leave this issue open as a reminder to address this!

**Comment by paxofsnax** [comment]
Got another of theses errors just selecting a source - `thread 'soundscape' panicked at 'attempt to calculate the remainder with a divisor of, src/lib/soundscape/movement/ngon.rs:74:19`
